# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'

    - name: Frontend Compilation (Syntax Check)
      run: |
        cd client
        find . -name "*.js" -exec node --check {} +

    - name: Backend Compilation (Syntax Check)
      run: |
        cd api
        find . -name "*.js" -exec node --check {} +

  gitleaks-scan:
    runs-on: Agent-1
    needs: compile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Remove gitleaks from tmp if it exist
        run: rm -f /tmp/gitleaks.tmp || echo "gitleaks.tmp has already been removed."

      - name: Gitleaks Setup
        uses: gitleaks/gitleaks-action@v2

      - name: Gitleaks Scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
      
  trivy_fs_scan:
    runs-on: Agent-1
    needs: gitleaks-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  sonar_frontend:
    runs-on: Agent-1
    needs: trivy_fs_scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: SonarCloud Scan for Frontend
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          projectBasedir: client
          args: >
            -Dsonar.projectKey=myapp_frontend_key
            -Dsonar.projectName=myapp_frontend_name
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/**.test.js,**/build/**
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

          
  sonar_backend:
    runs-on: Agent-1
    needs: sonar_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: SonarCloud Scan for Backend
        uses: SonarSource/sonarqube-scan-action@v4.1.0
        with:
          projectBasedir: api
          args: >
            -Dsonar.projectKey=myapp_backend_key
            -Dsonar.projectName=myapp_backend_name
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/**.test.js,**/build/**
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}